### PR TITLE
Product shape

### LINKED ISSUE #22: Ship helpers for preparing common patterns of input
I noticed when writing the repeatability test suite that the examples had repeated patterns in the input:
- f-plane Coriolis force field
- beta-plane Coriolis force field
- rectangular bordered pool geometry (i.e., the wetmask being all 1 except for a 1-cell border)

I think it's a good idea (in principle, no comment on priority) to ship helper functions that implement these patterns so that users doing basic things can get started more easily.

There is a choice about whether to implement those features in the Fortran core of MIM or in Python/Matlab/etc helper code that the project ships in conjunction with the Fortran.
- Pro Fortran: Implemented just once in one place (whereas, if there come to be both Python and Matlab frontends, these helpers will be duplicated across them and will need to be kept in sync).
- Pro Fortran: Feature is available to the hypothetical user that just compiles the Fortran and doesn't use any frontend.
- Pro frontend: Programming in Fortran is tedious and error-prone.
- Pro frontend: Helpers will be simple to unit-test (though, I don't know whether Matlab's unit testing framework(s) are any easier to use than Fortran's).
- Pro frontend: Additional such patterns will be easier to add, if there aren't very many frontends to which they need to be added.
- Pro frontend: Lower core maintenance burden and maintenance churn: If these helper functions change, the rest of the core does not need to be reverified, and does not even seem to need to be reverified.
- Pro frontend: Research results are more reproducible because the computed inputs are always present to be saved, and loaded from.  We can presumably minimize this point by dumping the computed inputs even if they are computed in Fortran, but I think that having that computation in the frontend(s) emphasizes the distinction more.

If Issue #21 is implemented, sinusoidal and stochastic wind will become two more such input patterns.

### LINKED ISSUE #62: Do we want to allow command-line overriding of parameters from `parameters.in`?
Then the semantics of `parameters.in` becomes that it's the default configuration, and command-line arguments take precedence.

Considerations:
- Probably mostly relevant during fast-iteration exploration, or when automating multi-run batches.
- Pro: Becomes easier to vary model runs, exploring subsets of parameter space.
- Pro: Becomes easier to automate varying parameter space.
- Con: This would be pretty annoying to implement in the Fortran core, but not too bad in a Python wrapper.

For the sake of reproducibility, would want the program to dump its full configuration to a human- and machine-readable file.

This becomes more useful in conjunction with automatically computing the gridded input files from resolution-dependent sources, so that the model resolution can be easily varied.

### LINKED ISSUE #95: Implement product shape
Here is the external interface to Aronnax as I see it:
- either `$ aronnax simulate [OPTIONS] [directory]` or
- `from aronnax import simulate; simulate(directory=".")`
- reads aronnax.conf from path indicated by option (default directory/aronnax.conf)
- merges other options into defaults given by aronnax.conf.  Notable options:
  - Paths to input data in NetCDF format
  - Pointers to input data as in-memory numpy arrays
  - Names of input data as named generator functions with parameters
  - Directory to use to communicate with the core (default main working directory)
  - Directory to place output files in NetCDF format (default main/output)
- compiles the core with desired compilation options if necessary
  - Should not depend on make, but do its own content hashing.
    - Can also accept arbitrary compile options, presumably postfix (with some presets)
    - Can also accept arbitrary run prefixes, like valgrind and perf (with some presets)
- saves the configuration for reproducibility (ideally without overwriting the input)
- generates input files
  - interpolates given inputs if necessary
    - options for interpolation method, one of which is "error if interpolation is needed"
  - writes parameters.in and needful input files to the core working directory
- invokes the core in the core working directory
- reads the core files and converts them to NetCDF output format
- there should be an in-Python version that skips the NetCDF output and presents ability to read the raw core outputs into memory one by one
- Option sections in the conf file:
  - Each of the sections in parameters.in
  - Output handling (paths, anything else)
  - Compilation options for the core
  - Run prefixes for debugging the core?
- A description of each parameter should appear in
  - The online help of the executable
  - The generated documentation of the top level Python function
  - Comments in the example aronnax.conf file
  - Maybe comments in the example parameters.in file
  - Comments in the aronnax.conf file the program writes
  - Maybe comments in the parameters.in file the program writes

### LINKED ISSUE #96: Discrepancy in dx values invalidates "known good" test outputs
The input generators in the test suite compute `dx` and `dy` as a function of the resolution, with a fixed total region size; whereas the core gets `dx` and `dy` values from the configuration file.  The latter is not kept in sync with the former, and they are, in the event, not equal, so the test suite runs with an inconsistent area configuration: input is generated assuming one spatial step size, but the simulation runs assuming another.

Work on #95 exposed this test suite problem; the blessed output will need to be regenerated.

### PR DESCRIPTION
**Pull request by axch**
Thorough rewrite of the Aronnax Python package, carrying out the packaging plan outlined in Issue #95 sufficiently that the remaining items are decoupled and incrementalizable.

Effects on issues:
- Closes #95, by construction, except for the parts not implemented. These will be filed as separate tickets.
- Closes #96.
- Makes progress toward #87, in that it is now much more clear what the UI of that package will be.
- Does not needlessly impede #67 (restartability), in that the full configuration of a run is written to disk before the run begins.
- Obsoletes and thus closes #62 (command-line overrides).  Its content is implemented in the interface of `driver.simulate`.
- Lays ground work for #30 (NetCDF output), in that there is now a workflow on which to hang any such output conversion.
- Unblocks #23 (user-facing examples), by defining the interface to make examples of.
- Closes #22 (input generation helpers), by defining them.

### CODE REVIEW

**Comment by edoddridge** [comment]
You weren't kidding - this is a serious rewrite!

I think I like the structure, but I'm struggling to get it running. After running `python setup.py install` the python files get copied over to a new directory under Anaconda, but they don't take the fortran core or the makefile with them. This means that `compile_core` tries to run in a directory without these files, and hence it fails. From some online sluething, it seems that we can use a `MANIFEST.in` file to make sure these files get copied across when the package is installed.

Unless I've missed something obvious?

**Comment by axch** [comment]
Travis seems to agree with you.  This is actually an old bug, but I think I know why it is manifesting now and didn't manifest earlier.  To wit, before, the .f90 file and the Makefile were, in effect, being searched for relative to the _test suite_ rather than relative to the _installed package_.

I also know why I didn't experience this problem during development: I had install Aronnax with `pip install -e .`, which creates symbolic links in the installation directory that point back at the source files.  This arrangement is convenient for iterating, because I don't have to reinstall every time I edit the source, but masks the problem that not enough files are, in fact, installed.  If that is a sufficient workaround for you to be able to continue the review, I'd like to think a bit on the best way to resolve this issue more permanently.

**Comment by edoddridge** [comment]
Thanks - using `pip install -e .` means that the test suite runs, and will let me continue the review.

**Comment by edoddridge** [comment]
Comments:
- I like the implementation of an input configuration file, that then gets altered and written to a new file to become the version that is used for the simulation and the basis of the `parameters.in` file for the fortran core.
- As we discussed, this PR introduces lots of undocumented features and code, but that documentation can be incrementally included as the code and interface are refined. I don't think there is any point delaying this PR while we make the documentation more complete. As we use this new interface I expect we'll find friction points and refine the code, thus necessitating changes to the documentation.


Things that I've changed:
- rename the beta_plane Coriolis functions to include an f in the name. Otherwise it seems like they refer to the velocities, rather than the grid locations.
- likewise, rename the f_plane Coriolis functions.
- make the `.travis.yml` file use the `pip install -e .` command so that it can run the test suite. Once this PR is merged, one of us should file a ticket to fix that issue.
- split the Coriolis functions and the wetmask function into separate sections in the documentation
- edit the docstring of `driver.simulate()` to indicate that aronnax-merged.conf` and `parameters.in` are generated automatically.
- added a section to the documentation called "Running Aronnax"

Questions:
- There is a function named `default_configuration`, but it doesn't seem to actually create a configuration file with the defaults, apart from setting the compile prefixes to false. Am I missing something? 
  - My conclusion from this is that it still requires the `aronnax.conf` file to exist and contain the defaults, which then get transferred to `aronnax-merged.conf` unless they are explicitly overwritten by the call to driver.simulate()`. I'm happy with that choice, but want to confirm that I've understood what is happening.
- Would it be polite to have the driver notice if the output directories already exist, and write to new ones with an incremented number appended? This might be a pain to implement in the fortran core, but could certainly be done with the python generated NetCDF output. A fairly major downside of this is that it would break the correspondence between the config files and the output - it would be possible to edit the config, rerun the simulation and end up with output and config files that came from different simulations.
- The `aronnax-merged.conf` files contain memory addresses for inputs that were generated from functions specified in `aronnax.conf`. Is that likely to be an issue for restarting simulations?

**Comment by axch** [comment]
Your changes look good to me.  To your questions:

- Yes, the `default_configuration` function is not a complete configuration, and `aronnax.conf` is required.  Its purpose is to set default values for parameters required by the driver program, so that the driver does not crash if `aronnax.conf` is missing some fields that have reasonable defaults.  It would be reasonable to extend this to provide sensible defaults for more parameters, especially "administrative" ones like `DumpWind`, but I actually think that forcing the user to look at the physics variables (e.g., by copying and modifying an example `aronnax.conf`) is better than trying to set defaults for them.  You also correctly noticed that `default_configuration` does not save a default configuration file; it just operates in memory.
- I don't think auto-incrementing names of directories is polite.  Instead, it would be reasonable to do any subset of
  - status quo, and warn users in the documentation to save expensive run outputs; or
  - abort before starting the core if the output directory exists and is not empty, expecting users to move old runs out of the way; or
  - teach the core to abort instead of overwriting a file that already exists; or
  - offer the user runtime control of the output directory, e.g. by adding one more configuration parameter for it, perhaps with some combination of the above; or
  - actually, offering the user runtime control of the _input_ directory accomplishes the same effect, because then they become free to control the output directory by controlling the working directory of the process; or
  - offering control of both directories; or
  - finally, as an additional option above and beyond setting the output directory, we can add an auto-increment feature; or possibly some other sort of autogeneration of the name, like a content hash of the configuration file and/or the inputs.
- If one provided an in-memory function to `driver.simulate`, one should not expect to be able to automatically rerun it from the merged configuration file alone.  (Actually, it is possible to try to provide that capability by saving that function in a Python pickle file, or some such, but that's a pain to think about.)  However, specifically restarting, specifically on the same system, can presumably be coded (as an additional feature) to skip the input specification and reuse the generated `.bin` input files.  Then it doesn't matter that the custom function cannot be directly recovered.  The same code can also cover the "tweak a parameter and rerun" use case.

Which of the above items are actionable enough to pull out as their own tickets, or as additions to tickets 102-106?

**Comment by axch** [comment]
Speaking of which, do you find that tickets 102-106 cover the gaps you see in this PR?  You specifically mentioned documentation, which is #103.

**Comment by edoddridge** [comment]
Cool. Thanks for the explanations.

I agree that forcing the user to think, at least briefly, about the physical parameters is a good idea. I was just a little thrown that a function called `default_configuration` doesn't actually create a default configuration. Expanding this function to cover the housekeeping parameters is probably worth its own ticket.

Honestly, I think the status quo with a warning in the documentation is probably the best option. So let's leave it as is and I'll open a ticket to add a warning to the docs.

I should have mentioned that 102-106 look good. Thanks for opening them.

**Pull request merged**
