### PR TITLE
Core terminal output

### PR DESCRIPTION
**Pull request by axch**
Conform interaction of the Aronnax core with terminal streams (namely, standard output and standard error) to unix conventions.  This includes fixes for #13 and #45.

### CODE REVIEW

**Comment by edoddridge** [comment]
What's the rationale behind leaving the zero in the `stop 0` command just before the `end program aronnax` command?

If one removes the zero, then the command doesn't print anything to stdout, and the run finishes with "Run finished at time step `n`, in `t` seconds." sent to stdout.

**Comment by axch** [comment]
Re: stop: Preservation of status quo, and I wasn't dealing with the `stop` statements.  Actually, scanning through the stop statements and making sure the core produces an appropriate exit code in every circumstance seems like a good idea.

**Comment by axch** [comment]
Re: seconds: It would be even more stylish to check whether the integer one is about to print is or is not equal to 1, and adjust the string to be singular or plural accordingly.

**Comment by axch** [comment]
Updated on both counts.

**Pull request merged**
