### PR TITLE
WIP: JOSS submission

### PR DESCRIPTION
**Pull request by edoddridge**
Working towards a manuscript for the [Journal of Open Source Software](http://joss.theoj.org/).

Things to do before submission:
 - [ ] tag a release, version 0.1
 - [x] update authors in the paper
 - [x] create metadata file

### CODE REVIEW

**Comment by axch** [comment]
Suggestion: Define "general circulation models" and "quasigeostrophic models".  Presumably each is given by some specific architectural choice, the way an "isopycnal model" approximates the ocean as homogeneous layers of varying depth.  I assume the gcms are the ones that approximate the ocean as voxels with fixed location but varying density; might be nice to say that, and also to give a succinct, lay-audience statement of what quasigeostrophic means.

It would also be stylish to work in an intuition for why isopycnal models can be very fast: one only needs two or three layers to get the same accuracy as from a 30-voxel-deep gcm.  However, I am not sure what statement is right, and where to work that in (and, even, whether to work it in).

**Comment by edoddridge** [comment]
I really like the new intro

We're now part way between US and British/Aus English: e.g. "modelling" vs "modeling", "idealised" vs "idealized". My vote is for Aus/British, but I'm not too fussed about it.

Currently working on the including definitions of quasigeostrophic and general circulation models.

**Comment by axch** [comment]
Definitely standardize dialects.  There is little that grates more than
spelling the same word in different ways in the same document.  I have no
objection to Aus/UK; it's just that I only know the American dialect, so I
can only draft in that one.

**Comment by edoddridge** [comment]
I've worked in lay definitions of 'general circulation model' and 'quasigeostrophic model'. They're not particularly precise, but I think they convey the important information in an accessible way. Defining general circulation models is a bit tricky, so I kept it very general and said they involve fewer approximations. Some general circulation models do use isopycnal coordinates, so the voxel vs layers distinction isn't helpful here.

One distinction between Aronnax and gcms is that Aronnax ignores thermodynamics (none of the processes that determine density are modelled), while gcms do include thermodynamics. I allude to this with "...the density difference between neighbouring layers is specified by the user." but we could be more explicit about it.

Sorry about misspelling your name earlier - I corrected it before pushing, but apparently forgot to commit the change.

**Comment by axch** [comment]
"dependencies that must be satisfied" -- are you talking about software dependencies, whose cost is installation burden?  If so, it would be clearer to say "are extremely complex, both to install, due to heavy software dependencies, and to operate, due to numerous free parameters."  If not, what did you mean?

Except for that, looks good to me.

**Comment by edoddridge** [comment]
I was, but on reflection, it's perhaps unfair to malign gcms for their external dependencies when Aronnax relies on MPI and gcc/gfortran. I've changed that bit to focus on the free parameters, and highlight that many must be specified prior to compiling the code.

I think we're ready.

**Comment by axch** [comment]
Looks good to me.

**Pull request merged**
